CREATE DATABASE IF NOT EXISTS chat_room;
USE chat_room;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    online VARCHAR(10) DEFAULT 'false',
    bookmarked VARCHAR(5000) DEFAULT '[]',
    pending VARCHAR(5000) DEFAULT '[]',
    friends VARCHAR(5000) DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS rooms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    admin VARCHAR(255) NOT NULL,
    users TEXT DEFAULT '',
    messages TEXT,
    muted VARCHAR(5000) DEFAULT '[]',
    banned VARCHAR(5000) DEFAULT '[]',
);
